---
- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart prometheus-blackbox-exporter
  ansible.builtin.service:
    name: prometheus-blackbox-exporter
    state: restarted

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
