openldap_base_suffix: "{{ ldap_suffix }}"
openldap_admin_cn: admin
openldap_admin_dn: "cn={{ openldap_admin_cn }},{{ openldap_base_suffix }}"
openldap_admin_password: "{{ ldap_admin_password }}"
openldap_people_ou: "ou=People,{{ openldap_base_suffix }}"
openldap_groups_ou: "ou=Groups,{{ openldap_base_suffix }}"
openldap_service_accounts_ou: "ou=ServiceAccounts,{{ openldap_base_suffix }}"
openldap_tls_cert: /etc/ssl/localcerts/ldap.pem
openldap_tls_key: /etc/ssl/localcerts/ldap.key
openldap_tls_ca: /etc/ssl/certs/ca-certificates.crt
